### ISSUE TITLE
Setting Hanna as default template doesn't work as documented

### ISSUE THREAD

**Issue by Aupajo** [mislav/hanna#1]
I get a multitude of errors using Hanna as an RDoc template when using anything but the `hanna` command itself, ranging from "could not find template 'hanna'" to deprecation warnings about `--inline-source` and invalid options `--format=html`. The README needs to be brought up-to-date by someone who knows how to fix it.

**Comment by Aupajo** [comment]
Apparently it's caused by RDoc 2.4.3 not being compatible with Hanna. RDoc 2.3.0 works fine though. If anyone's having this problem, just `gem uninstall rdoc` and `gem install rdoc -v 2.3.0`.

**Comment by Aupajo** [comment]
Sorry, makes a lot more sense now. Updated the Wiki to make a note about 2.3.0.

**Comment by mislav** [comment]
Thanks for updating the wiki. I'm currently in the process of rewriting Hanna for RDoc 2.4, stay tuned

**Comment by rdp** [comment]
thanks for your help with that.  Searchable class names would be quite sweet, too :D
