### ISSUE TITLE
Hanna, Bundler 0.9, and haml/sass 3 beta

### ISSUE THREAD

**Issue by perezd** [mislav/hanna#20]
When I try to bundle install, I get the following error --

No compatible versions could be found for required dependencies:
    Conflict on: "haml":
    \* haml (3.0.0.beta.2) activated by compass (= 0.10.0.rc3, runtime)
    \* haml (>= 3.0.0.beta.3, runtime) required by fancy-buttons (= 0.5.1, runtime)
    All possible versions of origin requirements conflict.

This error disappears if I take Hanna out of the Gemfile.

**Comment by mislav** [comment]
Yes, Hanna probably locks on older Haml in her own gem dependencies. Solution is, as you already found out, to take it out of your Gemfile. You don't need Hanna for runtime of your app anyway, so it doesn't really belong to the Gemfile. Hanna can be installed via RubyGems on the system and invoked when docs are needed.
