### ISSUE TITLE
Hanna clashes with HAML 3.0

### ISSUE THREAD

**Issue by sent-hil** [mislav/hanna#21]
I tried adding "  gem "hanna", '0.1.12', :require => 'hanna/rdoctask' to Teambox bundler file and I got this error.

No compatible versions could be found for required dependencies:
    Conflict on: "haml":
    \* haml (3.0.0.beta.1) activated by haml (~> 3.0.0.beta1, runtime)
    \* haml (~> 2.2.8, runtime) required by hanna (= 0.1.12, runtime)
    All possible versions of origin requirements conflict.

**Comment by mislav** [comment]
Don't add Hanna to Gemfile. It's a one-off tool, not something needed for the app's runtime. Simply install it on your system.
