### ISSUE TITLE
Deprecation warnings from sass?

### ISSUE THREAD

**Issue by jgn** [mislav/hanna#23]
hanna (0.1.12)
ruby 1.9.1
haml (3.0.12, 2.2.24)

DEPRECATION WARNING:
On line 276, character 3
Setting properties with = has been deprecated and will be removed in version 3.2.
Use "font-family: $title_font" instead.

You can use `sass-convert --in-place --from sass2 file.sass' to convert files automatically.

**Comment by mislav** [comment]
closing, duplicate of #22

thanks for reporting

**Comment by jgn** [comment]
Hey, sorry I missed the prior issue!
