### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by leejarvis** [mislav/hanna#27]
Hanna hasn't seen any action for 6 months now. It's still a favoured RDoc template for many people, which is why its forks have seen much more action. As a result of this it appears [Erik Hollensbe](https://github.com/erikh) has released the [hanna-nouveau](https://github.com/erikh/hanna-nouveau) gem, in an attempt to provide the original features and niceties of this great template, a fork whos latest version is fully compatible with the latest RDoc release. Is there any reason why these changes cannot be merged and Erik could continue to maintain the official Hanna source code? It would be a shame to see this gem die when there are people interested in maintaining it.

**Comment by Quintus** [comment]
The hanna-nouveau gem is really great, it even works with RDoc 3.4! Thanks for pointing this out, I frightened for hanna to just disappear...
The sources for the hanna-nouveau gem seem to have been removed from GitHub, although the gem is still in the RubyGems Index. What happened to them? 

Vale, 
Marvin

**Comment by raggi** [comment]
@quintus they're here: https://github.com/rdoc/hanna-nouveau

**Comment by Quintus** [comment]
I already knew this, nevertheless thank you.
